### ISSUE TITLE
Spherical harmonic coefficients

### ISSUE THREAD

**Issue by qzhu2017** [peterspackman/chmpy#3]
@peterspackman 
I asked my student @weiluntang89 to extract the spherical harmonics coefficients from chmpy so that we can reconstruct the surface shape. We did the following,
 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/29445366/195679383-9e74bac8-3a08-413b-b1eb-fdf2b4f2ce18.png">

But the output does not make sense to us. 
For a given l_max, the number of coefficients should be (l_max + 1)^2. Can you help?

**Comment by peterspackman** [comment]
That's true for complex valued functions! For real spherical harmonic transforms the coefficients satisfy $c_l^{-m} = \bar{c_l^{m}}$.

This means that there are only $(l_{\text{max}} + 1) (l_{\text{max}} + 2) / 2$ unique coefficients as the others are symmetry constrained, i.e. you can use a real valued FFT in the SHT and save significant computational expense.

To expand them out to the full set of coefficients I've written the convenience method here: https://github.com/peterspackman/chmpy/blob/00f2671a42256b4a0d0b028f0a80d94d564fd3af/chmpy/shape/_sht.pyx#L241

You could do the following:

``` python
from chmpy.shape._sht import expand_coeffs_to_full

full_coeffs = expand_coeffs_to_full(desc[0])
```

Apologies that wasn't clear, I should probably update the documentation in those functions, haven't had much time to work on this lately after rewriting the SHT code! Alternatively I could write it so the routines do this automatically for the user, which may be more intuitive.

**Comment by qzhu2017** [comment]
Great. Thanks for the clarification. I like the `expand_coeffs_to_full` function.

**Comment by qzhu2017** [comment]
@peterspackman 
Sorry for getting back to you later. I just did some quick test by following your suggestion.
```python
import numpy as np
from scipy.special import sph_harm

from chmpy import Crystal, Molecule
from chmpy.shape._sht import expand_coeffs_to_full

def expand(coeffs, N=4):
    """
    Compute the expansion of spherical function from coefs
    
    Args:
        coeffs: 1d array of f_lm
        N: number of sampled points per theta/phi
    """
    thetas = np.linspace(0, 2*np.pi, N)
    phis = np.linspace(0, np.pi, N)
    grids_t, grids_p = np.meshgrid(thetas, phis)
    
    lmax = int(np.sqrt(len(coeffs)))-1
    for theta, phi in zip(grids_t.flatten(), grids_p.flatten()):
        count = 0
        val = 0
        for l in range(lmax):
            for m in range(-l, l+1):
                val0 = coeffs[count] * sph_harm(m, l, theta, phi) 
                #print(l, m, np.degrees(theta), np.degrees(phi), val0)
                val += val0
                count += 1
        print("from scipy: {:6.1f} {:6.1f} ".format(np.degrees(theta), np.degrees(phi)), val)

# wget https://github.com/qzhu2017/PyXtal/blob/master/pyxtal/database/cifs/anthracene.cif
c = Crystal.load("anthracene.cif")
lmax = 4
coeff, desc = c.molecular_shape_descriptors(l_max = lmax , return_coefficients = True)
full_coeffs = expand_coeffs_to_full(lmax = lmax, coeffs = coeff[0])
#print(coeff[0].real)
#print(full_coeffs.real)

expand(full_coeffs.flatten())
```

The output function values for different grid points are:
```
from scipy:    0.0    0.0  (3.1654381870105257+0j)
from scipy:  120.0    0.0  (3.1654381870105257+0j)
from scipy:  240.0    0.0  (3.1654381870105257+0j)
from scipy:  360.0    0.0  (3.1654381870105257+0j)
from scipy:    0.0   60.0  (3.7176810086803482+0.7354784764731626j)
from scipy:  120.0   60.0  (3.04286263767503+1.148667045947533j)
from scipy:  240.0   60.0  (3.517058732197016-1.8841455224206956j)
from scipy:  360.0   60.0  (3.7176810086803482+0.7354784764731623j)
from scipy:    0.0  120.0  (3.717681108286948-0.7354784764731626j)
from scipy:  120.0  120.0  (3.0428627372816304-1.1486670459475328j)
from scipy:  240.0  120.0  (3.5170588318036162+1.884145522420695j)
from scipy:  360.0  120.0  (3.717681108286948-0.7354784764731621j)
from scipy:    0.0  180.0  (3.165438299370909+0j)
from scipy:  120.0  180.0  (3.165438299370909+0j)
from scipy:  240.0  180.0  (3.165438299370909+0j)
from scipy:  360.0  180.0  (3.165438299370909+0j)
```

Clearly, there are many points returning values with non-negligible imaginary components. Are they expected? Can you check if I did anything wrong?

Will you have time for a video chat?

**Comment by peterspackman** [comment]
Just to update on this, I've found the issue causing the imaginary values, there's an error in the phase factor in the `_expand_coeffs_to_full` method, it presently is based on the $l$ when it should be based on the $m$. I'll fix that.
The scipy spherical harmonics definitely have a different normalization convention but that can be addressed!
